Repository OasisLMF/OasisPlatform, pull requests merged in 2025-02, with the labels that each got.

#1163 Workaround for ods tools issue #174
  src/server/oasisapi/analysis_models/v1_api/tests/test_analysis_model.py
  src/server/oasisapi/analysis_models/v2_api/tests/test_analysis_model.py
  src/server/oasisapi/portfolios/models.py
  src/server/oasisapi/portfolios/v1_api/tests/test_portfolio.py
  src/server/oasisapi/portfolios/v2_api/tests/test_portfolio.py
Labels: bug, build system, LTS - 2.4

#1162 Fix/v2 location loading
  src/model_execution_worker/distributed_tasks.py
Labels: LTS - 2.4

#1158 Worker controller detects pending V1 task and tries to scale V2 workers
  kubernetes/worker-controller/src/autoscaler.py
Labels: bug, kubernetes, LTS - 2.3, LTS - 2.4

#1164 Fixed missing stack trace logging for V1 workers
  src/model_execution_worker/tasks.py
Labels: bug, LTS - 1.28, LTS - 2.3, LTS - 2.4

#1169 Azure Service Principal for Postgres SQL authentication -
  compose/postgres.docker-compose.yml
  requirements-server.in
  requirements-server.txt
  src/server/oasisapi/custom_db_backend/__init__.py
  src/server/oasisapi/custom_db_backend/base/__init__.py
  src/server/oasisapi/custom_db_backend/base/base.py
  src/server/oasisapi/custom_db_backend/readme.md
  src/server/oasisapi/settings.py
Labels: Enhancement, LTS - 1.28, LTS - 2.4

#1171 Update expected validation errors for ods-tools 4.0.1
  src/server/oasisapi/analysis_models/v1_api/tests/test_analysis_model.py
  src/server/oasisapi/analysis_models/v2_api/tests/test_analysis_model.py
Labels: LTS - 2.4

#1168 Pin drf-yasg package
  requirements-server.in
  requirements-server.txt
  requirements.txt
Labels: bug, LTS - 2.4

#1170 Azure Service Principal for Postgres SQL authentication - (#1169)
  requirements-server.in
  requirements-server.txt
  requirements-worker.txt
  requirements.txt
  src/server/oasisapi/custom_db_backend/__init__.py
  src/server/oasisapi/custom_db_backend/base/__init__.py
  src/server/oasisapi/custom_db_backend/base/base.py
  src/server/oasisapi/custom_db_backend/readme.md
  src/server/oasisapi/settings/base.py
Labels: Enhancement, LTS - 2.4
