Repository OasisLMF/OasisPlatform, pull requests merged in 2025-04, with the labels that each got.

#1183 Autoscale
  kubernetes/worker-controller/data/test/queue-status.json
  kubernetes/worker-controller/src/autoscaler.py
  kubernetes/worker-controller/src/oasis_websocket.py
  src/server/oasisapi/analyses/v2_api/utils.py
  src/server/oasisapi/analyses/v2_api/viewsets.py
  src/server/oasisapi/analysis_models/v2_api/serializers.py
  src/server/oasisapi/analysis_models/v2_api/viewsets.py
Labels: Enhancement, kubernetes, LTS - 2.4

#1193 Update base deb image to p3.12
  Dockerfile.model_worker_debian
Labels: bug, build system

#1189 Add internal worker to Helm charts
  kubernetes/charts/oasis-platform/templates/internal-worker.yaml
  kubernetes/charts/oasis-platform/values.yaml
  kubernetes/worker-controller/src/oasis_websocket.py
  scripts/minikube-deploy.sh
  src/model_execution_worker/server_tasks.py
  src/startup_worker.sh
Labels: Enhancement, kubernetes

#1194 Minikube CI/CD
  .github/workflows/minikube-cicd.yml
  scripts/get-minikube-logs.sh
Labels: kubernetes, build system

#1199 Store failed output failed V2 runs
  src/model_execution_worker/celery_request_handler.py
  src/model_execution_worker/distributed_tasks.py
  src/model_execution_worker/utils.py
  src/server/oasisapi/analyses/v2_api/task_controller.py
  src/server/oasisapi/analyses/v2_api/tasks.py
Labels: bug, LTS - 2.4

#1198 Fix User-data file loading
  src/model_execution_worker/utils.py
Labels: bug, production, LTS - 2.4

#1201 Udate name in workflow so Job type is clear in GitHub UI
  .github/workflows/minikube-cicd.yml
Labels: build system

#1204 Valkey
  kubernetes/charts/oasis-models/values.yaml
  kubernetes/charts/oasis-platform/values.yaml
Labels: Enhancement, kubernetes

#1187 Alerts on completion of analysis (Issue #1185)
  kubernetes/worker-controller/src/autoscaler.py
  src/server/oasisapi/analyses/apps.py
  src/server/oasisapi/analyses/models.py
  src/server/oasisapi/analyses/v1_api/tests/test_analysis_model.py
  src/server/oasisapi/analyses/v2_api/signal_receivers.py
  src/server/oasisapi/analyses/v2_api/tests/test_analysis_model.py
  src/server/oasisapi/queues/consumers.py
Labels: Enhancement
