Repository OasisLMF/OasisPlatform, pull requests merged in 2025-09, with the labels that each got.

#1255 Update server to Django 5 to support DB connection pools
  compose/debug.docker-compose.yml
  compose/s3.docker-compose.yml
  conf.ini
  docker-compose.yml
  kubernetes/charts/oasis-models/templates/_helpers.tpl
  kubernetes/charts/oasis-platform/templates/_helpers.tpl
  kubernetes/worker-controller/requirements.in
  kubernetes/worker-controller/requirements.txt
  requirements-server.in
  requirements-server.txt
  requirements-worker.in
  requirements-worker.txt
  requirements.txt
  src/server/oasisapi/analyses/v1_api/tasks.py
  src/server/oasisapi/analyses/v1_api/urls.py
  src/server/oasisapi/analyses/v2_api/tasks.py
  src/server/oasisapi/analyses/v2_api/tests/test_analysis_model.py
  src/server/oasisapi/analyses/v2_api/urls.py
  src/server/oasisapi/analysis_models/v1_api/urls.py
  src/server/oasisapi/analysis_models/v2_api/urls.py
  src/server/oasisapi/asgi.py
  src/server/oasisapi/auth/tests/test_jwt.py
  src/server/oasisapi/auth/urls.py
  src/server/oasisapi/base_urls.py
  src/server/oasisapi/custom_db_backend/base/base.py
  src/server/oasisapi/data_files/v1_api/urls.py
  src/server/oasisapi/data_files/v2_api/urls.py
  src/server/oasisapi/files/v1_api/urls.py
  src/server/oasisapi/files/v2_api/urls.py
  src/server/oasisapi/info/views.py
  src/server/oasisapi/portfolios/v1_api/urls.py
  src/server/oasisapi/portfolios/v2_api/urls.py
  src/server/oasisapi/queues/consumers.py
  src/server/oasisapi/queues/routing.py
  src/server/oasisapi/queues/tests/test_consumers.py
  src/server/oasisapi/queues/tests/test_middleware.py
  src/server/oasisapi/queues/urls.py
  src/server/oasisapi/routing.py
  src/server/oasisapi/settings/base.py
  src/server/oasisapi/swagger.py
  src/server/oasisapi/urls.py
Labels: production, LTS - 2.4

#1274 Fixed mysql DB settings
  compose/mysql.docker-compose.yml
  src/server/oasisapi/settings/base.py
Labels: bug, production, LTS - 2.4

#1275 Fixed UI timeout issue
  kubernetes/charts/oasis-monitoring/values.yaml
  kubernetes/charts/oasis-platform/Chart.lock
  kubernetes/charts/oasis-platform/Chart.yaml
  kubernetes/charts/oasis-platform/charts/ingress-nginx-4.0.6.tgz
  kubernetes/charts/oasis-platform/charts/traefik-37.1.0.tgz
  kubernetes/charts/oasis-platform/templates/cluster-issuer.yaml
  kubernetes/charts/oasis-platform/templates/ingress.yaml
  kubernetes/charts/oasis-platform/templates/oasis_server.yaml
  kubernetes/charts/oasis-platform/values.yaml
  kubernetes/scripts/k8s/host_volume_shell.sh
  kubernetes/scripts/k8s/upload_piwind_model_data.sh
  scripts/minikube-deploy.sh
Labels: bug, production, LTS - 2.4

#1242 Progress bar in platform with websocket
  compose/debug.docker-compose.yml
  docker-compose.yml
  kubernetes/charts/oasis-models/values.yaml
  requirements-worker.txt
  scripts/minikube-deploy.sh
  src/model_execution_worker/distributed_tasks.py
  src/model_execution_worker/tasks.py
  src/model_execution_worker/tests/test_tasks.py
  src/server/oasisapi/analyses/migrations/0017_auto_20250730_1011.py
  src/server/oasisapi/analyses/models.py
  src/server/oasisapi/analyses/v1_api/serializers.py
  src/server/oasisapi/analyses/v1_api/tests/test_analysis_api.py
  src/server/oasisapi/analyses/v1_api/viewsets.py
  src/server/oasisapi/analyses/v2_api/serializers.py
  src/server/oasisapi/analyses/v2_api/tests/test_analysis_api.py
  src/server/oasisapi/analyses/v2_api/viewsets.py
  src/server/oasisapi/queues/consumers.py
  src/server/oasisapi/queues/routing.py
Labels: Enhancement, LTS - 2.4
