Repository OasisLMF/OasisPlatform, pull requests merged in 2025-08, with the labels that each got.

#1249 Fix/CVE aug 2025 2.4.x
  Dockerfile.api_server
  kubernetes/worker-controller/requirements.txt
  requirements-server.in
  requirements-server.txt
  requirements-worker.in
  requirements-worker.txt
  requirements.in
  requirements.txt
  scripts/bind-requirements.sh
  scripts/unbind-requirements.sh
  scripts/update-packages.sh
  scripts/update-requirements.py
Labels: security, LTS - 2.4

#1256 fix/analysis settings template `_ns_update`
  src/server/oasisapi/analysis_models/models.py
Labels: LTS - 2.3, LTS - 2.4

#1250 Fix/CVE aug 2025 2.3.x
  Dockerfile.api_server
  kubernetes/worker-controller/requirements.txt
  requirements-server.in
  requirements-server.txt
  requirements-worker.in
  requirements-worker.txt
  requirements.in
  requirements.txt
  scripts/bind-requirements.sh
  scripts/unbind-requirements.sh
  scripts/update-packages.sh
  scripts/update-requirements.py
Labels: security, LTS - 2.3
