Repository OasisLMF/OasisPlatform, pull requests merged in 2025-01, with the labels that each got.

#1152 Expose components versions in API
  src/model_execution_worker/utils.py
  src/server/oasisapi/analyses/v2_api/tasks.py
  src/server/oasisapi/analysis_models/migrations/0010_auto_20241209_1632.py
  src/server/oasisapi/analysis_models/models.py
  src/server/oasisapi/analysis_models/v2_api/serializers.py
  src/server/oasisapi/info/models.py
  src/server/oasisapi/info/tests/test_info.py
  src/server/oasisapi/info/views.py
  src/server/oasisapi/schemas/custom_swagger.py
Labels: Enhancement

#1155 Feature/1097 track subtask retries
  src/model_execution_worker/celery_request_handler.py
  src/server/oasisapi/analyses/migrations/0016_auto_20250115_1304.py
  src/server/oasisapi/analyses/models.py
  src/server/oasisapi/analyses/v2_api/serializers.py
  src/server/oasisapi/analyses/v2_api/task_controller.py
  src/server/oasisapi/analyses/v2_api/tasks.py
  src/server/oasisapi/analyses/v2_api/viewsets.py
Labels: Enhancement, LTS - 2.4

#1160 Fix/testing oed4 update
  src/server/oasisapi/analysis_models/v1_api/tests/test_analysis_model.py
  src/server/oasisapi/analysis_models/v2_api/tests/test_analysis_model.py
  src/server/oasisapi/portfolios/v1_api/tests/test_portfolio.py
  src/server/oasisapi/portfolios/v2_api/tests/test_portfolio.py
Labels: build system, LTS - 2.4

#1161 Fix/hooks file loading
  src/model_execution_worker/distributed_tasks.py
Labels: LTS - 2.4
